import { Nunito} from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700","800","900"]
});

export const metadata = {
  title: "BamFitOut",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">  
      <body className={nunito.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
